In [71]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data
from tensorflow.contrib.layers import fully_connected

# mnist = input_data.read_data_sets("MNIST_data", one_hot=True)
# shapes = pd.read_csv('./data/vectors_1.csv')
shapes = pd.read_csv('./data/vectors_pillow.csv')
# remove the first index col
shapes = shapes.iloc[:,1:]
print(shapes.shape)

(66, 6162)


In [72]:
# Params

num_inputs = 6162    #28x28 pixels
num_hid1 = 1000
num_hid2 = 10
num_hid3 = num_hid1
num_output = num_inputs
lr = 0.01
actf = tf.nn.relu


In [73]:
# Create Layers 

X = tf.placeholder(tf.float32,shape=[None,num_inputs])
initializer = tf.variance_scaling_initializer()

w1=tf.Variable(initializer([num_inputs,num_hid1]),dtype=tf.float32)
w2=tf.Variable(initializer([num_hid1,num_hid2]),dtype=tf.float32)
w3=tf.Variable(initializer([num_hid2,num_hid3]),dtype=tf.float32)
w4=tf.Variable(initializer([num_hid3,num_output]),dtype=tf.float32)

b1=tf.Variable(tf.zeros(num_hid1))
b2=tf.Variable(tf.zeros(num_hid2))
b3=tf.Variable(tf.zeros(num_hid3))
b4=tf.Variable(tf.zeros(num_output))

hid_layer1=actf(tf.matmul(X,w1) + b1)
hid_layer2=actf(tf.matmul(hid_layer1,w2) + b2)
hid_layer3=actf(tf.matmul(hid_layer2,w3) + b3)
output_layer=actf(tf.matmul(hid_layer3,w4) + b4)

loss = tf.reduce_mean(tf.square(output_layer-X))

optimizer = tf.train.AdamOptimizer(lr)
train = optimizer.minimize(loss)

init = tf.global_variables_initializer()

In [94]:
num_epoch=10
batch_size=150
num_test_images=10
num_train = shapes.shape[0]

loss_epoch_log = []

builder = tf.saved_model.builder.SavedModelBuilder('./tmp/saved_model')

with tf.Session() as sess:
    sess.run(init)
    for epoch in range(num_epoch):
        
        # num_batches=mnist.train.num_examples//batch_size
        
#         num_batches=num_train//batch_size
#         for iteration in range(num_batches):
#             # X_batch,y_batch=mnist.train.next_batch(batch_size)
#             X_batch = shapes
#             sess.run(train,feed_dict={X:X_batch})
            
        sess.run(train,feed_dict={X:shapes})
            
        train_loss=loss.eval(feed_dict={X:shapes})
        print("epoch {} loss {}".format(epoch,train_loss))
        
        loss_epoch_log.append({ 'epoch': epoch, 'train_loss': train_loss })
        
    results=output_layer.eval(feed_dict={X:shapes}, session=sess)
    print('results')
        
    print(results)
    # Show loss graph
#     loss_epoch_log = pd.DataFrame(loss_epoch_log)
#     plt.scatter(loss_epoch_log.epoch, loss_epoch_log.train_loss)
#     plt.show()
    
    # Creating signatures
    tensor_info_x = tf.saved_model.utils.build_tensor_info(X)
    tensor_info_hid2 = tf.saved_model.utils.build_tensor_info(hid_layer2)
    tensor_info_output_layer = tf.saved_model.utils.build_tensor_info(output_layer)
    
    encode_signature = (
        tf.saved_model.signature_def_utils.build_signature_def(
              inputs={'input_vector': tensor_info_x},
              outputs={'code': tensor_info_hid2},
              method_name='encode'))
    
    decode_signature = (
        tf.saved_model.signature_def_utils.build_signature_def(
              inputs={'code': tensor_info_hid2},
              outputs={'output_vector': tensor_info_output_layer},
              method_name='encode'))
    
    # Saving the model
    builder.add_meta_graph_and_variables(
        sess, [tf.saved_model.tag_constants.SERVING], 
        signature_def_map={
            'encode': encode_signature,
            'decode': decode_signature
        },
        strip_default_attrs=True)
    builder.save()
    

    # Save the model
#     saver = tf.train.Saver()
#     save_path = saver.save(sess, "./tmp/model.ckpt")
#     print('saved at', save_path)
    
    
#     tf.saved_model.simple_save(sess,
#             './tmp/simple_save',
#             inputs={"X": shapes},
#             outputs={"output_layer": output_layer })
#     print('saved with simple save')
    
    print('w1', w1.eval())
    
    # Do Random Inputs
    vec = output_layer.eval(feed_dict={hid_layer2: np.random.rand(100,10)}, session=sess)
    df = pd.DataFrame(vec)
    df.to_csv('./data/results_random_1.csv')
    # print(df)
    
    

epoch 0 loss 0.00022191960306372494
epoch 1 loss 0.00018514803377911448
epoch 2 loss 0.00015582030755467713
epoch 3 loss 0.0001317892165388912
epoch 4 loss 0.0001249249035026878
epoch 5 loss 0.00013317225966602564
epoch 6 loss 0.0001352311228401959
epoch 7 loss 0.0001275313552469015
epoch 8 loss 0.00012075276754330844
epoch 9 loss 0.00011985548189841211
results
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
INFO:tensorflow:No assets to save.
INFO:tensorflow:No assets to write.
INFO:tensorflow:SavedModel written to: ./tmp/saved_model/saved_model.pb
w1 [[ 0.04052284  0.00449252  0.05928428 ...  0.04356372  0.00334816
   0.05328922]
 [ 0.01946063 -0.00336884 -0.00550745 ...  0.01329082 -0.02386573
   0.03730151]
 [ 0.03850732  0.02717582  0.02533472 ...  0.04356769 -0.02201555
   0.02435702]
 ...
 [ 0.01504729  0.01642638 -0.00264257 ...  0.02398222  0.00919385
   0.00573164]
 [-0.

In [89]:
out_df = pd.DataFrame(results)
out_df.to_csv('./data/out_4.csv')

# Output is not so varying
#out_df.std()


In [75]:
# Encode
saver = tf.train.Saver()

with tf.Session() as sess:
    # Restore variables from disk.
    saver.restore(sess, "/tmp/model.ckpt")
    print("Model restored.")
    # vec = sess.run(hid_layer2, feed_dict={X:shapes})
    # print(vec.shape)
    # df = pd.DataFrame(vec)
    # df.to_csv('./data/pillow_encoded.csv')
    # print(df)
    
    vec = output_layer.eval(feed_dict={hid_layer2: np.random.rand(100,10)}, session=sess)
    df = pd.DataFrame(vec)
    df.to_csv('./data/results_random_2.csv')
    
    
# Decode

INFO:tensorflow:Restoring parameters from /tmp/model.ckpt
Model restored.
